apiVersion: apps/v1
kind: Deployment
metadata:
  name: myntra
  labels:
    app: myntra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myntra
  template:
    metadata:
      labels:
        app: myntra
    spec:
      containers:
        - name: myntra
          image: 329869042877.dkr.ecr.ap-south-1.amazonaws.com/b12:7ffc9ca30407c93de35f32345cabc258602d1d9b
          ports:
            - containerPort: 3000
