apiVersion: apps/v1
kind: Deployment
metadata:
  name: myntra
  labels:
    app: myntra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myntra
  template:
    metadata:
      labels:
        app: myntra
    spec:
      containers:
        - name: myntra
          image: 329869042877.dkr.ecr.ap-south-1.amazonaws.com/b12:1dc9e55495fdd77801e3708f48c64e618d742cac
          ports:
            - containerPort: 3000
